<a href="https://colab.research.google.com/github/SallBryant/Nerual-Net-Simple-example/blob/main/zhengqi%E7%89%B9%E5%BE%81%E4%BC%98%E5%8C%96.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

train_data_file = "zhengqi_train.txt"
test_data_file =  "zhengqi_test.txt"

train_data = pd.read_csv(train_data_file, sep='\t', encoding='utf-8')
test_data = pd.read_csv(test_data_file, sep='\t', encoding='utf-8')

In [1]:
epsilon=1e-5

#组交叉特征，可以自行定义，如增加： x*x/y, log(x)/y 等等
func_dict = {
            'add': lambda x,y: x+y,
            'mins': lambda x,y: x-y,
            'div': lambda x,y: x/(y+epsilon),
            'multi': lambda x,y: x*y
            }

In [3]:
def auto_features_make(train_data,test_data,func_dict,col_list):
    train_data, test_data = train_data.copy(), test_data.copy()
    for col_i in col_list:
        for col_j in col_list:
            for func_name, func in func_dict.items():
                for data in [train_data,test_data]:
                    func_features = func(data[col_i],data[col_j])
                    col_func_features = '-'.join([col_i,func_name,col_j])
                    data[col_func_features] = func_features
    return train_data,test_data

In [4]:
train_data2, test_data2 = auto_features_make(train_data,test_data,func_dict,col_list=test_data.columns)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  if __name__ == '__main__':

In [5]:
train_data2.describe()

,V0,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V37-div-V35,V37-multi-V35,V37-add-V36,V37-mins-V36,V37-div-V36,V37-multi-V36,V37-add-V37,V37-mins-V37,V37-div-V37,V37-multi-V37
count,2888.000000,2888.000000,2888.000000,2888.000000,2888.000000,2888.000000,2888.000000,2888.000000,2888.000000,2888.000000,...,2888.000000,2888.000000,2888.000000,2888.000000,2888.000000,2888.000000,2888.000000,2888.0,2888.000000,2888.000000
mean,0.123048,0.056068,0.289720,-0.067790,0.012921,-0.558565,0.182892,0.116155,0.177856,-0.169452,...,-0.254082,-0.103943,-0.099672,-0.160988,-0.066244,-0.042967,-0.260659,0.0,0.999667,1.051315
std,0.928031,0.941515,0.911236,0.970298,0.888377,0.517957,0.918054,0.955116,0.895444,0.953813,...,13.759849,1.332133,1.378113,1.433573,35.860056,1.100326,2.034392,0.0,0.018614,1.453538
min,-4.335000,-5.122000,-3.420000,-3.956000,-4.742000,-2.182000,-4.576000,-5.048000,-4.692000,-12.891000,...,-399.126092,-13.997014,-6.116000,-5.633000,-763.316583,-7.270890,-7.260000,0.0,0.000000,0.000000
25%,-0.297000,-0.226250,-0.313000,-0.652250,-0.385000,-0.853000,-0.310000,-0.295000,-0.159000,-0.390000,...,-1.255585,-0.345618,-0.994250,-1.084250,-1.322569,-0.356641,-1.596500,0.0,0.999988,0.104814
50%,0.359000,0.272500,0.386000,-0.044500,0.110000,-0.466000,0.388000,0.344000,0.362000,0.042000,...,-0.097139,-0.021067,-0.139500,-0.313000,-0.094212,-0.009971,-0.371000,0.0,1.000007,0.469225
75%,0.726000,0.599000,0.918250,0.624000,0.550250,-0.154000,0.831250,0.782250,0.726000,0.042000,...,1.108110,0.295677,0.696750,0.588500,1.141533,0.255847,0.990500,0.0,1.000017,1.409563
max,2.121000,1.918000,2.828000,2.457000,2.689000,0.489000,1.895000,1.918000,2.245000,1.335000,...,165.293383,17.894308,6.079000,5.196000,813.065327,9.226570,6.000000,0.0,1.010101,13.176900

In [6]:
from sklearn.decomposition import PCA   #主成分分析法

#PCA方法降维
pca = PCA(n_components=500)

train_data2_pca = pca.fit_transform(train_data2.iloc[:,0:-1])
test_data2_pca = pca.transform(test_data2)

train_data2_pca = pd.DataFrame(train_data2_pca)
test_data2_pca = pd.DataFrame(test_data2_pca)

train_data2_pca['target'] = train_data2['target']

train_data2_pca.describe()

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- V37-multi-V37
Feature names seen at fit time, yet now missing:
- target

  warnings.warn(message, FutureWarning)

,0,1,2,3,4,5,6,7,8,9,...,491,492,493,494,495,496,497,498,499,target
count,2.888000e+03,2.888000e+03,2.888000e+03,2.888000e+03,2.888000e+03,2.888000e+03,2.888000e+03,2.888000e+03,2.888000e+03,2.888000e+03,...,2.888000e+03,2.888000e+03,2.888000e+03,2.888000e+03,2.888000e+03,2.888000e+03,2.888000e+03,2.888000e+03,2.888000e+03,2888.000000
mean,-1.049084e-14,1.720458e-13,6.739724e-13,-6.318713e-13,5.412722e-13,-3.109412e-13,7.369913e-14,-1.123583e-13,2.758520e-14,2.431395e-13,...,-4.989555e-15,-2.590233e-14,-1.398389e-15,1.275188e-14,-8.610841e-15,-2.996310e-14,2.420840e-14,9.411370e-15,1.190430e-14,0.126353
std,2.091689e+04,2.051415e+04,1.881760e+04,1.534087e+04,1.489172e+04,1.432094e+04,1.198707e+04,1.196798e+04,1.174319e+04,1.122425e+04,...,1.045547e+01,1.038683e+01,1.033814e+01,1.028811e+01,1.022499e+01,1.017682e+01,1.011893e+01,1.010668e+01,1.006520e+01,0.983966
min,-1.225698e+04,-6.839004e+03,-1.755562e+05,-5.700327e+03,-4.272156e+03,-4.642403e+05,-3.723564e+05,-6.577846e+03,-2.817842e+03,-2.324602e+04,...,-7.700990e+01,-6.114129e+01,-5.498464e+01,-5.108298e+01,-6.166352e+01,-5.236283e+01,-7.045570e+01,-5.764122e+01,-5.171236e+01,-3.044000
25%,-3.838940e+02,-4.707459e+02,-5.213718e+02,-2.824593e+02,-4.737717e+02,-1.247274e+02,-5.539020e+01,-2.202587e+02,-2.457762e+02,-2.023575e+02,...,-4.732099e+00,-4.621944e+00,-5.045350e+00,-5.102411e+00,-4.799419e+00,-4.427329e+00,-4.618597e+00,-5.212228e+00,-4.661344e+00,-0.350250
50%,-3.821804e+02,-4.695499e+02,-5.194192e+02,-2.811182e+02,-4.706962e+02,-1.223626e+02,-5.342086e+01,-2.187775e+02,-2.437651e+02,-2.002766e+02,...,6.948562e-02,2.025337e-02,-8.486729e-02,-3.415015e-02,1.323444e-02,8.644532e-03,7.364520e-03,-1.084906e-02,-1.050477e-02,0.313000
75%,-3.805605e+02,-4.684238e+02,-5.175277e+02,-2.797327e+02,-4.676280e+02,-1.202092e+02,-5.150380e+01,-2.173191e+02,-2.411016e+02,-1.978688e+02,...,4.933896e+00,4.939170e+00,4.682258e+00,4.267373e+00,4.860515e+00,4.605374e+00,4.791200e+00,4.851272e+00,4.797412e+00,0.793250
max,1.123613e+06,1.062884e+06,7.198868e+05,8.240925e+05,5.496216e+05,5.822955e+05,5.255021e+05,6.428801e+05,6.263484e+05,6.025213e+05,...,1.665832e+02,6.754154e+01,8.734999e+01,8.224602e+01,7.901910e+01,6.301771e+01,7.678835e+01,6.503048e+01,6.488606e+01,2.538000

In [11]:
X_train2 = train_data2[test_data2.columns].values
y_train = train_data2['target']

print(X_train2.shape)
y_train.shape

(2888, 5814)

(2888,)

In [ ]:
# ls_validation i
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error
import lightgbm as lgb
import numpy as np

# 5折交叉验证
Folds=5
kf = KFold(len(X_train2), n_splits=Folds, random_state=2019, shuffle=True)
# 记录训练和预测MSE
MSE_DICT = {
    'train_mse':[],
    'test_mse':[]
}

# 线下训练预测
for i, (train_index, test_index) in enumerate(kf.split(X_train2)):
    # lgb树模型
    lgb_reg = lgb.LGBMRegressor(
        learning_rate=0.01,
        max_depth=-1,
        n_estimators=5000,
        boosting_type='gbdt',
        random_state=2019,
        objective='regression',
    )
   
    # 切分训练集和预测集
    X_train_KFold, X_test_KFold = X_train2[train_index], X_train2[test_index]
    y_train_KFold, y_test_KFold = y_train[train_index], y_train[test_index]
    
    # 训练模型
    lgb_reg.fit(
            X=X_train_KFold,y=y_train_KFold,
            eval_set=[(X_train_KFold, y_train_KFold),(X_test_KFold, y_test_KFold)],
            eval_names=['Train','Test'],
            early_stopping_rounds=100,
            eval_metric='MSE',
            verbose=50
        )


    # 训练集预测 测试集预测
    y_train_KFold_predict = lgb_reg.predict(X_train_KFold,num_iteration=lgb_reg.best_iteration_)
    y_test_KFold_predict = lgb_reg.predict(X_test_KFold,num_iteration=lgb_reg.best_iteration_) 
    
    print('第{}折 训练和预测 训练MSE 预测MSE'.format(i))
    train_mse = mean_squared_error(y_train_KFold_predict, y_train_KFold)
    print('------\n', '训练MSE\n', train_mse, '\n------')
    test_mse = mean_squared_error(y_test_KFold_predict, y_test_KFold)
    print('------\n', '预测MSE\n', test_mse, '\n------\n')
    
    MSE_DICT['train_mse'].append(train_mse)
    MSE_DICT['test_mse'].append(test_mse)
print('------\n', '训练MSE\n', MSE_DICT['train_mse'], '\n', np.mean(MSE_DICT['train_mse']), '\n------')
print('------\n', '预测MSE\n', MSE_DICT['test_mse'], '\n', np.mean(MSE_DICT['test_mse']), '\n------')